apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-service-gateway-ingress
  namespace: peerprep
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      set $room_service_host http://room-service-api-service;

      location ~ /room-service/rooms/?$ {
        limit_except GET {
            deny all;
        }

        proxy_pass $room_service_host;
      }
spec:
  rules:
    - host: peerprep.us.to
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webpage-service-api-service
                port:
                  number: 9010
          - path: /user-service
            pathType: Prefix
            backend:
              service:
                name: user-service-api-service
                port:
                  number: 9000
          - path: /question-service
            pathType: Prefix
            backend:
              service:
                name: question-service-api-service
                port:
                  number: 9001
          - path: /matching-service
            pathType: Prefix
            backend:
              service:
                name: matching-service-api-service
                port:
                  number: 9002
          - path: /room-service
            pathType: Prefix
            backend:
              service:
                name: room-service-api-service
                port:
                  number: 9003
          - path: /webpage-service
            pathType: Prefix
            backend:
              service:
                name: webpage-service-api-service
                port:
                  number: 9010
